var game_file_list = [
	"GameApp.js",
	"LoadingUI.js",
	"control/ScriptController.js",
	"control/ScriptObject.js",
	"control/MainController.js",
	"model/GameSetting.js",
	"model/RoleManager.js",
	"model/ValueObject.js",
	"model/SceneVO.js",
	"model/RoleVO.js",
	"support/GameObject.js",
	"support/IAiScript.js",
	"utils/Utils.js",
	"view/SceneGround.js",
	"view/SceneObject.js",
	"view/RoleObject.js",
	"script/Cowboy.js",
	"script/GameMain.js",
	"view/GameScene.js",
	"model/Context.js",];
var document_class = "GameApp";